permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: codergma
  email: codergma@163.com
  link: http://codergma.com
  github: http://github.com/codergma
  music: http://site.douban.com/linanya

# 站点信息
title: codergma的博客
description: My personal blog
url: http://codergma.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# disqus 设置
disqus:
  shortname: codergma

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档